pipeline {
    agent any

    stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }
    
    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }
    
  // environment {
  //     ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
  //   }

  //    stages{
  //     stage("Initial cleanup") {
  //         steps {
  //           dir("${WORKSPACE}") {
  //             deleteDir()
  //           }
  //         }
  //       }

  //     stage('Checkout SCM') {
  //        steps{
  //           git branch: 'feature/jenkinspipeline-stages2', url: 'https://github.com/onyeka-hub/ansible-config-mgt.git'
  //        }
  //      }

  //     stage('Prepare Ansible For Execution') {
  //       steps {
  //         sh 'echo ${WORKSPACE}' 
  //         sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'  
  //       }
  //    }

  //     stage('Run Ansible playbook') {
  //       steps {
  //          ansiblePlaybook become: true, colorized: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/dev.yml', playbook: 'playbooks/site.yml'
  //        }
  //     }

  //     stage('Clean Workspace after build'){
  //       steps{
  //         cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
  //       }
  //     }
   }
}
