---
# - hosts: db
# - name: import db files
#   import_playbook: ../static-assignments/database.yml

# - hosts: nginx
# - name: nginx assignment
#   import_playbook: ../static-assignments/nginx.yml
 
# - hosts: artifactory
# - name: artifactory assignment
#   import_playbook: ../static-assignments/artifactory.yml


- hosts: todo
- name: Deploy the todo application
  import_playbook: ../static-assignments/deployment.yml
